name: omnigram
version: 1.0.2
publish_to: none
description: A Audio Book project.
environment:
  sdk: ">=3.5.3-0 <4.0.0"

dependencies:

  flutter:
    sdk: flutter
  pretty_dio_logger: ^1.3.1
  dio: ^5.7.0
  hive_flutter: ^1.1.0
  flutter_easyloading: ^3.0.5
  highlight: ^0.7.0
  url_launcher: ^6.1.12
  markdown: ^7.1.1
  flutter_markdown: ^0.6.17
  share_plus: ^10.0.2
  flutter_svg: ^2.0.7
  cached_network_image: ^3.2.3
  flutter_highlight: ^0.7.0
  path_provider: ^2.0.15
  hooks_riverpod: ^2.5.3
  riverpod_annotation: ^2.5.3
  go_router: ^14.2.7
  universal_platform: ^1.0.0+1
  test: ^1.24.9
  json_annotation: ^4.8.1
  desktop_window: ^0.4.0
  adaptive_components: ^0.0.9
  flutter_adaptive_scaffold: ^0.1.7+1
  flutter_highlighter: ^0.1.1
  sse_stream: ^1.0.2

  epubx:
    git: 
      url: https://github.com/lxpio/epubx.dart.git
      ref: v4.0.2
  # epubx:
  #   path: ../epubx.dart

  flutter_slidable: ^3.0.0
  transparent_image: ^2.0.1
  flutter_hooks: ^0.20.3
  scrollable_positioned_list: ^0.3.8
  flutter_html: ^3.0.0-beta.2
  just_audio: ^0.9.36
  lottie: ^3.0.0
  simple_animations: ^5.0.2
  easy_localization: ^3.0.7
  isar: ^4.0.0-dev.14
  isar_flutter_libs: ^4.0.0-dev.14
  timezone: ^0.9.4
  device_info_plus: ^10.1.2
  openapi:
    path: openapi
  flutter_udid: ^3.0.0
  logging: ^1.2.0
  # macros: ^0.1.3-main.0

#dependency_overrides:
#  collection: ^1.19.0

dev_dependencies:
  flutter_lints: ^4.0.0
  # flutter_test:
  #   sdk: flutter
  build_runner: ^2.4.11
  flutter_launcher_icons: "^0.13.1"
  custom_lint: ^0.5.2  
  riverpod_lint: ^2.0.1
  riverpod_generator: ^2.3.1
  json_serializable: ^6.7.1
  analyzer: ^6.7.0



  

flutter:
  uses-material-design: true
  generate: true # Add this line
  assets:
    - assets/images/
    - assets/files/
    - assets/i18n/





flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/logo-white.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/images/logo-white-s.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/images/logo-white-s.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/images/logo-white-s.png"


