name: docs

on:
  push:
    branches:
      - main # Set a branch name to trigger deployment
  pull_request:


jobs:
  build:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
    - uses: actions/checkout@v4
    - name: Setup pnpm
      uses: pnpm/action-setup@v2
      with:
        version: 8.3.1
    - uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'pnpm'
        cache-dependency-path: docs/pnpm-lock.yaml
    - name: Install dependencies
      run: |
        cd docs
        pnpm install
    - name: Build
      run: |
        cd docs
        pnpm run build
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
        # If you're changing the branch from main,
        # also change the `main` in `refs/heads/main`
        # below accordingly.
      if: github.ref == 'refs/heads/main'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs/build
    - name: Deploy To Qcloud
      uses: burnett01/rsync-deployments@6.0.0
      with:
        switches: -avzr --delete
        path: ./docs/build
        remote_host: ${{ secrets.QCLOUD_HOST }}
        remote_port: ${{ secrets.QCLOUD_PORT }}
        remote_path: ${{ vars.DEPLOY_PATH }}
        remote_user: ${{ secrets.DEPLOY_USER }}
        remote_key: ${{ secrets.DEPLOY_KEY }}